### ISSUE TITLE
Unable to install on UXG

### ISSUE THREAD

**Issue by noumenon272** [tusc/wireguard-kmod#26]
I posted this to reddit, but this is probably a better place to ask my question:

I’m trying to install for UXG. I initially had a permission denied error (for root user) and had to chmod +x the setup_wireguard.sh script. I then get this error when trying to install 7-9-21:

```
# ./setup_wireguard.sh 
loading wireguard...
insmod: can't insert '/mnt/data/wireguard/wireguard-4.1.37-v1.9.0-4.3493-b965822.ko': No such file or directory
insmod: can't insert '/mnt/data/wireguard/iptable_raw-4.1.37-v1.9.0-4.3493-b965822.ko': No such file or directory
insmod: can't insert '/mnt/data/wireguard/ip6table_raw-4.1.37-v1.9.0-4.3493-b965822.ko': No such file or directory
```

and this error when trying to install 8-10-21:

```
# ./setup_wireguard.sh 
loading wireguard...
Unsupported Kernel version 4.1.37-v1.9.0-4.3493-b965822
```

I’m running the following kernel:
```

# uname -a
Linux UXGRouter 4.1.37-v1.9.0-4.3493-b965822 #1 SMP Fri Apr 23 15:44:21 UTC 2021 aarch64 GNU/Linux
```

thoughts?
thanks

**Comment by peacey** [comment]
The package doesn't currently have that module version. I can add it in the next couple of hours, but have you tried to upgrade your UXG 1.11.0-15? That version should be supported already.

**Comment by noumenon272** [comment]
I haven’t yet upgraded to 1.11. it looks like there have been a lot of issues with assigning WAN1 to the SFP port, which is what I’m doing. But the unifi forums are also a big negative feedback loop so its hard to tell how significant this issue is. Seems there may be a few big bugs in that new firmware though.

**Comment by peacey** [comment]
@noumenon272, please try the latest release now, this version has been added now. Just run the following:

```sh
curl -LJo wireguard-kmod.tar.Z https://github.com/tusc/wireguard-kmod/releases/download/v8-10-21/wireguard-kmod-08-10-21.tar.Z
tar -C /mnt/data -xvzf wireguard-kmod.tar.Z
cd /mnt/data/wireguard
chmod +x setup_wireguard.sh
./setup_wireguard.sh
```
Btw, we have never tested this on the UXG (only tested on UDM/P). So tell us how it goes.

**Comment by noumenon272** [comment]
I just tried it and I get a similar error.

```
# ./setup_wireguard.sh
ln: /bin/bash: File exists
ln: /usr/bin/htop: File exists
ln: /usr/sbin/iftop: File exists
ln: /sbin/resolvconf: File exists
loading wireguard...
Unsupported Kernel version 4.1.37-v1.9.0-4.3493-b965822
```

**Comment by peacey** [comment]
Sorry, I had a typo in the version. Please try the commands again, it should be correct this time.

**Comment by noumenon272** [comment]
Progress, but still no success. I get:

```
# ./setup_wireguard.sh 
loading wireguard...
```
but then it hangs. If I hit return the SSH connection is dropped.

**Comment by peacey** [comment]
Unfortunately, that sounds like the kernel is crashing because the module is not compatible with the UXG. Is the UDMP restarting after the SSH connection is dropped? Can you check the output of this after SSHing in again after the drop?

```
cat /sys/fs/pstore/console-ramoops-0
```
The thing is, we are compiling the modules from the UDM kernel sources. We do not have the UXG kernel sources. If the UXG kernel differs from the UDM, then the module will crash the kernel as you seem to be experiencing. We would need the UXG kernel sources from Ubiquiti to compile the module properly for the UXG. I was hoping the kernels are the same but it seems there are a few modifications between them. 

Alternatively, starting in 1.11.0, Ubiquiti included the WireGuard kernel module, so maybe they did the same for the UXG 1.11.0? I know you said you don't want to upgrade, but I would try to upgrade your UXG to 1.11.0 and see if you can run setup_wireguard.sh on it then, and if the module loads and doesn't crash... You can always downgrade back to 1.9.0-4 if you're having issues with 1.11.0 or WireGuard doesn't work there either.

**Comment by noumenon272** [comment]
yup. kernel panic

`[  722.392086] Kernel panic - not syncing: Fatal exception in interrupt`

i’ll give 1.11 a shot and let you know.

**Comment by peacey** [comment]
Thanks @noumenon272. If 1.11 doesn't work, one more thing we can attempt for 1.9.0-4 is to compile using the kernel config for 1.9.0-4. If only the config changed and not the sources, it might work so worth a shot. So if 1.11 doesn't work, please downgrade back to 1.9.0-4 and then run this command to obtain the config. Copy and paste the output to a text file and upload it to your reply.

```sh
zcat /proc/config.gz
```

Make sure you include the entire contents from when you ran the command to the end (it's long).

**Comment by noumenon272** [comment]
well that was a hot mess. 1.11 was a disaster for me. I’ve since done a factory reset on my UXG and finally have everything back up and running.

[file.txt](https://github.com/tusc/wireguard-kmod/files/7232142/file.txt)

**Comment by peacey** [comment]
Thanks @noumenon272. Will try to compile it with the config now. But did you try to load the module on 1.11? Did it not work or what happened?

**Comment by noumenon272** [comment]
Sorry, I didn't try. My entire network went down and my uxg stopped resolving dns, and as a result my controller lost contact with the uxg. I bailed and reverted back to 1.9.

**Comment by peacey** [comment]
@noumenon272, I've recompiled it with your config. Please redownload it and run the same commands as before and see what happens.

**Comment by noumenon272** [comment]
success! thanks for all your help.

**Comment by peacey** [comment]
> success! thanks for all your help.

That's great to hear! Did not expect it to work honestly. Have you tested being able to bring up a tunnel and route traffic through it yet?

**Comment by noumenon272** [comment]
No, I just got it installed. 

I started setup, but haven't had a chance to fully test yet.

**Comment by peacey** [comment]
No worries. Please report back once you fully test you can route through the tunnel, that would be great so we could document that it works on the UXG! 

Thank you so much!

**Comment by noumenon272** [comment]
ah, no luck. I’m not getting a handshake and nothing is routing.

**Comment by peacey** [comment]
If you are getting a handshake, most likely that means it's working because the handshake wouldn't work otherwise. Most likely, there is an issue with your configuration. Can you explain what your configuration is? 

Can you ping the server internal VPN IP from the UDMP?

**Comment by noumenon272** [comment]
I'm NOT getting a handshake.

`# wg
interface: wg0
  public key: server public key
  private key: (hidden)
  listening port: 51820

peer: client public key
  allowed ips: 192.168.5.0/24`

server conf:

`[Interface]                                                               
Address = 192.168.5.1                                                     
ListenPort = 51820                                                        
PrivateKey = server private key                
                                                                          
[Peer]                                                                    
PublicKey = client public key                 
AllowedIPs = 192.168.5.2/24 `

client conf:

`[Interface]
Address = 192.168.5.2
ListenPort = 21841
PrivateKey = client private key
DNS = 192.168.1.2

[Peer]
PublicKey = server public key
Endpoint = FQDN:51820
AllowedIPs = 192.168.5.0/24`

I'm pretty sure my firewall and connectivity is all working correctly as I am able to connect to a docker instance of wireguard on my home server. everything connects and routes correctly through there. (as I was typing this out I realized I did not turn off my port forwarding rule for wireguard, but I just tried that too with the same result).

**Comment by noumenon272** [comment]
@peacey 
Am I just out of luck on this kernel build?

**Comment by peacey** [comment]
Sorry @noumenon272. I didn't realize you said you did NOT get a handshake. It's difficult to debug with your config when I don't have the UXG. Do you think you can download this Mullvad wireguard configuration on your UXG (I created a temporary key for testing), wg-quick up it, and see if you get a handshake? Make sure not to have any other wireguard configs active before testing. Example, run the following to download and bring the config up.

```sh
mkdir /mnt/data/wg-test
cd /mnt/data/wg-test
curl -L https://pastebin.com/raw/QCMjBkNk | sed -e 's/\r//g' > wg0.conf
wg-quick up ./wg0.conf
```

After it's up, check if you are getting a handshake via `wg`, and also try to ping 1.1.1.1 through the tunnel directly on the UXG like this:

```sh
ping -I wg0 1.1.1.1
```

Make sure to `wg-quick down ./wg0.conf` when you're done testing because the configuration routes 1.1.1.1 through it and will mess up your DNS if you use that server for your DNS.

Btw, are you behind NAT or does your router have a public IP? And if you have any firewall rules, maybe disable them for testing.

Please try that and tell me what happens with the ping and handshake.

**Comment by peacey** [comment]
Hey @noumenon272,

Beta version 1.11.0-16 is out now. Do you maybe want to try that and see if it includes the wireguard module?

**Comment by noumenon272** [comment]
I got it working! running the new firmware 1.11.0-16-3888 on the UXG.

thanks for all your help.

After all that I have now realized that there does not seem to be a way to run a boot script on the UXG to make it persistent.

**Comment by cainmp** [comment]
I also was able to get this to work on my UXG-Pro running 1.11.0-16. The lack of a startup script is a problem, so hopefully someone has an idea on how to solve that.

**Comment by peacey** [comment]
Thanks everyone for testing. This issue is resolved now, so I will close this. 

As for the startup script, unfortunately there doesn't seem to be a known way to do that on the UXG yet. If anyone figures it out, feel free to share it with us.

Have a nice day!
